# config/meta.yml

meta_product_name: "Trabby"
meta_title: "Trabby - Plan your next trip"
meta_description: "Our mission is to is to help people around the world to plan and experience the perfect trip"
meta_image: "og-image.png"
